site_name: tarpitd.py

repo_url: https://github.com/ImBearChild/tarpitd.py/
edit_uri: blob/master/docs/

nav:
  - Home: index.md
  - Guide: getting-started.md
  - Manual: 
    - Index: manual/index.md
    - manual/tarpitd.py.1.md
    - manual/tarpitd.conf.5.md
  - About: about.md