[project]
name = "tarpitd"
version = "0.0.1"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
"tarpitd.py" = "tarpitd:main_cli"

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"] 